---
name: ceph-objectstorage-broker

instance_groups:
- name: ceph-objectstorage-broker
  azs: [z1]
  instances: 1
  vm_type: minimal
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: ceph-objectstorage-broker
    release: ceph-objectstorage-broker
    properties:
      broker:
        env:
          rados_access_key: ((rados_access_key))
          rados_secret_key: ((rados_secret_key))
          rados_endpoint: ((rados_endpoint))
          rados_admin: ((rados_admin))
          broker_username: ((broker_username))
          broker_password: ((broker_password))
          s3_path: ((s3_path))
          swift_path: ((swift_path))
          bucket_name: ((bucket_name))
          instance_limit: ((instance_limit))
          instance_prefix: ((instance_prefix))
          use_https: ((use_https))
        service:
          id: "d70715af-9d44-441e-ad8e-229c25491c5f"
          name: "Ceph-Object-Storage"
          description: "Swift and S3 object storage service based on a Ceph backend."
          tags:
          - "Object Storage"
          - "Swift"
          - "S3"
          - "1000 Buckets/Containers"
          metadata:
            displayName: "Ceph Object Storage"
            longDescription: "Swift and S3 object storage service based on a Ceph backend"
            providerDisplayName: "ZHAW"
          plan_updateable: true
          plans:
          - id: "7e4804d1-91f2-4f48-aa26-cb51a8fef225"
            name: "100MB"
            description: "100MB object storage"
            free: true
            metadata:
              displayName: "100MB"
              quotaMB: "100"
          - id: "d8ff5e56-99a2-4a83-b938-2046a13d4b6e"
            name: "500MB"
            description: "500MB object storage"
            free: true
            metadata:
              displayName: "500MB"
              quotaMB: "500"
          - id: "58572e37-bbfc-4033-9ff8-b4e35b350858"
            name: "1GB"
            description: "1GB object storage"
            free: true
            metadata:
              displayName: "1GB"
              quotaMB: "1000"
          - id: "959cd029-341c-40e4-9b03-0351e85064c0"
            name: "2GB"
            description: "2GB object storage"
            free: true
            metadata:
              displayName: "2GB"
              quotaMB: "2000"
          - id: "92b7c9fd-21b9-4fe3-a3bc-082559bc5588"
            name: "5GB"
            description: "5GB object storage"
            free: true
            metadata:
              displayName: "5GB"
              quotaMB: "5000"

variables:
- name: broker_password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
  max_in_flight: 1

releases:
- name: ceph-objectstorage-broker
  url: https://github.com/icclab/ceph-objectstore-broker-boshrelease/releases/download/V1.2.1/cosb-release-1.2.1.tgz
  version: latest